### PR TITLE
there's a method for that.

### PR DESCRIPTION
**Pull request by kch**
@jkakar

### CODE REVIEW

**Comment by kch** [comment]
I don't know why it had to be `URI.encode_www_form_component` instead of just `URI.encode`, but the latter doesn't escape `@`.

**Comment by jkakar** [comment]
+1!

**Comment by geemus** [comment]
Should we nuke that gsub also then?

**Comment by kch** [comment]
Ah duh can't believe I left that there. Will update.

**Comment by geemus** [comment]
@kch easy to do, thanks!

**Comment by kch** [comment]
done.

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
